services:
  db:
#    image: postgres:16-alpine
    image: pgvector/pgvector:pg16
    container_name: jobosint-postgres
    hostname: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
