services:
  db:
    image: postgres:15.0-alpine
    container_name: jobosint-postgres
    hostname: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
