insert into jobosint.public.company(name, website_url) values('Affirm', 'https://www.affirm.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Ascension', 'https://healthcare.ascension.org') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Atlassian', 'https://www.atlassian.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Autodesk', 'https://www.autodesk.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Aviatrix', 'https://aviatrix.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Axon', 'https://www.axon.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Block', 'https://block.xyz') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Blue Owl, LLC', 'https://www.blueowl.xyz') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Calm', 'https://www.calm.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Canonical', 'https://canonical.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Cash App', 'https://cash.app') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Circle', 'https://www.circle.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Cisco', 'https://www.cisco.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('DigitalOcean', 'https://www.digitalocean.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Dragos', 'https://www.dragos.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Earnin', 'https://www.earnin.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('F5', 'https://www.f5.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Facebook', 'https://www.facebook.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Fastly', 'https://www.fastly.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Fermyon', 'https://www.fermyon.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Fly.io', 'https://www.fly.io') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Google', 'https://www.google.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Harness', 'https://harness.io') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Hashicorp', 'https://www.hashicorp.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Hubspot', 'https://www.hubspot.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Intuit', 'https://intuit.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Isovalent', 'https://isovalent.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Iterative Health', 'https://iterative.health') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('JetBrains', 'https://jetbrains.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Kraken', 'https://www.kraken.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Microsoft', 'https://www.microsoft.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Mixpanel', 'https://mixpanel.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Nuna', 'https://nuna.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('NVIDIA', 'https://www.nvidia.com/en-us') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Ockam', 'https://www.ockam.io') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Overjet', 'https://www.overjet.ai') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Paxos', 'https://paxos.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Paypal', 'https://www.paypal.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Pulumi', 'https://www.pulumi.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Red Hat', 'https://www.redhat.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Reddit', 'https://www.reddit.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Replit', 'https://replit.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Rippling', 'https://www.rippling.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Salesforce', 'https://www.salesforce.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Segment', 'https://segment.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Shopify', 'https://www.shopify.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Sofi', 'https://sofi.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Solo', 'https://solo.io') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Sourcegraph', 'https://about.sourcegraph.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Spotify', 'https://www.spotify.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Square', 'https://squareup.com/us/en') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Stripe', 'https://stripe.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Submittable', 'https://www.submittable.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Surepoint', 'https://surepoint.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Svix', 'https://www.svix.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Tetrate', 'https://www.tetrate.io') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Upbound', 'https://www.upbound.io') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Veeva Systems', 'https://www.veeva.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Vercel', 'https://vercel.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Vida Health', 'https://www.vida.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Vivint', 'https://www.vivint.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Zillow', 'https://www.zillow.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.company(name, website_url) values('Human Interest', 'https://humaninterest.com') ON CONFLICT DO NOTHING;
insert into jobosint.public.job(title, company, url) values('Senior Software Engineer', (select id from jobosint.public.company where name = 'Google'), 'https://google.com/jobs/senior-software-engineer') ON CONFLICT DO NOTHING;
insert into jobosint.public.job(title, company, url) values('Analyst', (select id from jobosint.public.company where name = 'Microsoft'), 'https://microsoft.com/jobs/analyst') ON CONFLICT DO NOTHING;
