insert into jobosint.jobosint.company(name, website_url) values('Affirm', 'https://www.affirm.com');
insert into jobosint.jobosint.company(name, website_url) values('Ascension', 'https://healthcare.ascension.org');
insert into jobosint.jobosint.company(name, website_url) values('Atlassian', 'https://www.atlassian.com');
insert into jobosint.jobosint.company(name, website_url) values('Autodesk', 'https://www.autodesk.com');
insert into jobosint.jobosint.company(name, website_url) values('Aviatrix', 'https://aviatrix.com');
insert into jobosint.jobosint.company(name, website_url) values('Axon', 'https://www.axon.com');
insert into jobosint.jobosint.company(name, website_url) values('Block', 'https://block.xyz');
insert into jobosint.jobosint.company(name, website_url) values('Blue Owl, LLC', 'https://www.blueowl.xyz');
insert into jobosint.jobosint.company(name, website_url) values('Calm', 'https://www.calm.com');
insert into jobosint.jobosint.company(name, website_url) values('Canonical', 'https://canonical.com');
insert into jobosint.jobosint.company(name, website_url) values('Cash App', 'https://cash.app');
insert into jobosint.jobosint.company(name, website_url) values('Circle', 'https://www.circle.com');
insert into jobosint.jobosint.company(name, website_url) values('Cisco', 'https://www.cisco.com');
insert into jobosint.jobosint.company(name, website_url) values('DigitalOcean', 'https://www.digitalocean.com');
insert into jobosint.jobosint.company(name, website_url) values('Dragos', 'https://www.dragos.com');
insert into jobosint.jobosint.company(name, website_url) values('Earnin', 'https://www.earnin.com');
insert into jobosint.jobosint.company(name, website_url) values('F5', 'https://www.f5.com');
insert into jobosint.jobosint.company(name, website_url) values('Facebook', 'https://www.facebook.com');
insert into jobosint.jobosint.company(name, website_url) values('Fastly', 'https://www.fastly.com');
insert into jobosint.jobosint.company(name, website_url) values('Fermyon', 'https://www.fermyon.com');
insert into jobosint.jobosint.company(name, website_url) values('Fly.io', 'https://www.fly.io');
insert into jobosint.jobosint.company(name, website_url) values('Google', 'https://www.google.com');
insert into jobosint.jobosint.company(name, website_url) values('Harness', 'https://harness.io');
insert into jobosint.jobosint.company(name, website_url) values('Hashicorp', 'https://www.hashicorp.com');
insert into jobosint.jobosint.company(name, website_url) values('Hubspot', 'https://www.hubspot.com');
insert into jobosint.jobosint.company(name, website_url) values('Intuit', 'https://intuit.com');
insert into jobosint.jobosint.company(name, website_url) values('Isovalent', 'https://isovalent.com');
insert into jobosint.jobosint.company(name, website_url) values('Iterative Health', 'https://iterative.health');
insert into jobosint.jobosint.company(name, website_url) values('JetBrains', 'https://jetbrains.com');
insert into jobosint.jobosint.company(name, website_url) values('Kraken', 'https://www.kraken.com');
insert into jobosint.jobosint.company(name, website_url) values('Microsoft', 'https://www.microsoft.com');
insert into jobosint.jobosint.company(name, website_url) values('Mixpanel', 'https://mixpanel.com');
insert into jobosint.jobosint.company(name, website_url) values('Nuna', 'https://nuna.com');
insert into jobosint.jobosint.company(name, website_url) values('NVIDIA', 'https://www.nvidia.com/en-us');
insert into jobosint.jobosint.company(name, website_url) values('Ockam', 'https://www.ockam.io');
insert into jobosint.jobosint.company(name, website_url) values('Overjet', 'https://www.overjet.ai');
insert into jobosint.jobosint.company(name, website_url) values('Pacific Northwest National Laboratory', 'https://www.pnnl.gov/news');
insert into jobosint.jobosint.company(name, website_url) values('Paxos', 'https://paxos.com');
insert into jobosint.jobosint.company(name, website_url) values('Paypal', 'https://www.paypal.com');
insert into jobosint.jobosint.company(name, website_url) values('Pulumi', 'https://www.pulumi.com');
insert into jobosint.jobosint.company(name, website_url) values('Red Hat', 'https://www.redhat.com');
insert into jobosint.jobosint.company(name, website_url) values('Reddit', 'https://www.reddit.com');
insert into jobosint.jobosint.company(name, website_url) values('Replit', 'https://replit.com');
insert into jobosint.jobosint.company(name, website_url) values('Rippling', 'https://www.rippling.com');
insert into jobosint.jobosint.company(name, website_url) values('Salesforce', 'https://www.salesforce.com');
insert into jobosint.jobosint.company(name, website_url) values('Segment', 'https://segment.com');
insert into jobosint.jobosint.company(name, website_url) values('Shopify', 'https://www.shopify.com');
insert into jobosint.jobosint.company(name, website_url) values('Sofi', 'https://sofi.com');
insert into jobosint.jobosint.company(name, website_url) values('Solo', 'https://solo.io');
insert into jobosint.jobosint.company(name, website_url) values('Sourcegraph', 'https://about.sourcegraph.com');
insert into jobosint.jobosint.company(name, website_url) values('Spotify', 'https://www.spotify.com');
insert into jobosint.jobosint.company(name, website_url) values('Square', 'https://squareup.com/us/en');
insert into jobosint.jobosint.company(name, website_url) values('Stripe', 'https://stripe.com');
insert into jobosint.jobosint.company(name, website_url) values('Submittable', 'https://www.submittable.com');
insert into jobosint.jobosint.company(name, website_url) values('Surepoint', 'https://surepoint.com');
insert into jobosint.jobosint.company(name, website_url) values('Svix', 'https://www.svix.com');
insert into jobosint.jobosint.company(name, website_url) values('Tetrate', 'https://www.tetrate.io');
insert into jobosint.jobosint.company(name, website_url) values('Upbound', 'https://www.upbound.io');
insert into jobosint.jobosint.company(name, website_url) values('Veeva Systems', 'https://www.veeva.com');
insert into jobosint.jobosint.company(name, website_url) values('Vercel', 'https://vercel.com');
insert into jobosint.jobosint.company(name, website_url) values('Vida Health', 'https://www.vida.com');
insert into jobosint.jobosint.company(name, website_url) values('Vivint', 'https://www.vivint.com');
insert into jobosint.jobosint.company(name, website_url) values('Zillow', 'https://www.zillow.com');
insert into jobosint.jobosint.company(name, website_url) values('Human Interest', 'https://humaninterest.com');